In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

In [ ]:
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1').text

In [ ]:
soup= BeautifulSoup(webpage,'lxml')

In [ ]:
company=soup.find_all('div',class_='company-content-wrapper')

In [ ]:
len(company)

30

In [ ]:
name=[]
rating=[]
reviews=[]
ctype=[]
hq=[]
how_old=[]
no_of_employee=[]

for i in company:

  name.append(i.find('h2').text.strip())
  rating.append(i.find('p',class_='rating').text.strip())
  reviews.append(i.find('a' , class_='review-count').text.strip())
  ctype.append(i.find_all('p',class_='infoEntity')[0].text.strip())
  hq.append(i.find_all('p',class_='infoEntity')[1].text.strip())
  how_old.append(i.find_all('p',class_='infoEntity')[2].text.strip())
  no_of_employee.append(i.find_all('p',class_='infoEntity')[3].text.strip())

df=pd.DataFrame({'name':name,
   'rating':rating,
   'reviews':reviews,
   'company_type':ctype,
   'Head_Quarters':hq,
   'Company_Age':how_old,
   'No_of_Employee':no_of_employee,
   })

In [ ]:
df.head(2)

,name,rating,reviews,company_type,Head_Quarters,Company_Age,No_of_Employee
0,TCS,3.9,(47.4k Reviews),Public,"Mumbai,Maharashtra + 267 more",54 years old,1 Lakh+ Employees (India)
1,Accenture,4.2,(31.4k Reviews),Public,Dublin + 140 more,33 years old,1 Lakh+ Employees (India)

In [ ]:
final=pd.DataFrame()
for j in range(1,1001):
  print(j,"out of 1001")
  webpage=requests.get('https://www.ambitionbox.com/list-of-companies?page={}'.format(j)).text
  soup=BeautifulSoup(webpage,'lxml')
  company=soup.find_all('div',class_='company-content-wrapper')
  name=[]
  rating=[]
  reviews=[]
  ctype=[]
  hq=[]
  how_old=[]
  no_of_employee=[]

  for i in company:
#    print(company.index(i),"out of {}".format(len(company)))

    try:
       name.append(i.find('h2').text.strip())
    except:
       name.append(np.nan)

    try:
       rating.append(i.find('p',class_='rating').text.strip())
    except:
       rating.append(np.nan)
   
    try:

      reviews.append(i.find('a' , class_='review-count').text.strip())
    except:
      reviews.append(np.nan)

    try:

      ctype.append(i.find_all('p',class_='infoEntity')[0].text.strip())
    except:
      ctype.append(np.nan)
    try:

      hq.append(i.find_all('p',class_='infoEntity')[1].text.strip())
    except:
      hq.append(np.nan)
    
    try:

      how_old.append(i.find_all('p',class_='infoEntity')[2].text.strip())
    except:
      how_old.append(np.nan)
    try:
      no_of_employee.append(i.find_all('p',class_='infoEntity')[3].text.strip())
    except:
      no_of_employee.append(np.nan)
    

  df=pd.DataFrame({'name':name,
    'rating':rating,
    'reviews':reviews,
    'company_type':ctype,
    'Head_Quarters':hq,
    'Company_Age':how_old,
    'No_of_Employee':no_of_employee,
    })
  
  final=final.append(df,ignore_index=True)

1 out of 1001
2 out of 1001
3 out of 1001
4 out of 1001
5 out of 1001
6 out of 1001
7 out of 1001
8 out of 1001
9 out of 1001
10 out of 1001
11 out of 1001
12 out of 1001
13 out of 1001
14 out of 1001
15 out of 1001
16 out of 1001
17 out of 1001
18 out of 1001
19 out of 1001
20 out of 1001
21 out of 1001
22 out of 1001
23 out of 1001
24 out of 1001
25 out of 1001
26 out of 1001
27 out of 1001
28 out of 1001
29 out of 1001
30 out of 1001
31 out of 1001
32 out of 1001
33 out of 1001
34 out of 1001
35 out of 1001
36 out of 1001
37 out of 1001
38 out of 1001
39 out of 1001
40 out of 1001
41 out of 1001
42 out of 1001
43 out of 1001
44 out of 1001
45 out of 1001
46 out of 1001
47 out of 1001
48 out of 1001
49 out of 1001
50 out of 1001
51 out of 1001
52 out of 1001
53 out of 1001
54 out of 1001
55 out of 1001
56 out of 1001
57 out of 1001
58 out of 1001
59 out of 1001
60 out of 1001
61 out of 1001
62 out of 1001
63 out of 1001
64 out of 1001
65 out of 1001
66 out of 1001
67 out of 1001
68 out of 1001
69 out of 1001
70 out of 1001
71 out of 1001
72 out of 1001
73 out of 1001
74 out of 1001
75 out of 1001
76 out of 1001
77 out of 1001
78 out of 1001
79 out of 1001
80 out of 1001
81 out of 1001
82 out of 1001
83 out of 1001
84 out of 1001
85 out of 1001
86 out of 1001
87 out of 1001
88 out of 1001
89 out of 1001
90 out of 1001
91 out of 1001
92 out of 1001
93 out of 1001
94 out of 1001
95 out of 1001
96 out of 1001
97 out of 1001
98 out of 1001
99 out of 1001
100 out of 1001
101 out of 1001
102 out of 1001
103 out of 1001
104 out of 1001
105 out of 1001
106 out of 1001
107 out of 1001
108 out of 1001
109 out of 1001
110 out of 1001
111 out of 1001
112 out of 1001
113 out of 1001
114 out of 1001
115 out of 1001
116 out of 1001
117 out of 1001
118 out of 1001
119 out of 1001
120 out of 1001
121 out of 1001
122 out of 1001
123 out of 1001
124 out of 1001
125 out of 1001
126 out of 1001
127 out of 1001
128 out of 1001
129 out of 1001
130 out of 1001
131 out of 1001
132 out of 1001
133 out of 1001
134 out of 1001
135 out of 1001
136 out of 1001
137 out of 1001
138 out of 1001
139 out of 1001
140 out of 1001
141 out of 1001
142 out of 1001
143 out of 1001
144 out of 1001
145 out of 1001
146 out of 1001
147 out of 1001
148 out of 1001
149 out of 1001
150 out of 1001
151 out of 1001
152 out of 1001
153 out of 1001
154 out of 1001
155 out of 1001
156 out of 1001
157 out of 1001
158 out of 1001
159 out of 1001
160 out of 1001
161 out of 1001
162 out of 1001
163 out of 1001
164 out of 1001
165 out of 1001
166 out of 1001
167 out of 1001
168 out of 1001
169 out of 1001
170 out of 1001
171 out of 1001
172 out of 1001
173 out of 1001
174 out of 1001
175 out of 1001
176 out of 1001
177 out of 1001
178 out of 1001
179 out of 1001
180 out of 1001
181 out of 1001
182 out of 1001
183 out of 1001
184 out of 1001
185 out of 1001
186 out of 1001
187 out of 1001
188 out of 1001
189 out of 1001
190 out of 1001
191 out of 1001
192 out of 1001
193 out of 1001
194 out of 1001
195 out of 1001
196 out of 1001
197 out of 1001
198 out of 1001
199 out of 1001
200 out of 1001
201 out of 1001
202 out of 1001
203 out of 1001
204 out of 1001
205 out of 1001
206 out of 1001
207 out of 1001
208 out of 1001
209 out of 1001
210 out of 1001
211 out of 1001
212 out of 1001
213 out of 1001
214 out of 1001
215 out of 1001
216 out of 1001
217 out of 1001
218 out of 1001
219 out of 1001
220 out of 1001
221 out of 1001
222 out of 1001
223 out of 1001
224 out of 1001
225 out of 1001
226 out of 1001
227 out of 1001
228 out of 1001
229 out of 1001
230 out of 1001
231 out of 1001
232 out of 1001
233 out of 1001
234 out of 1001
235 out of 1001
236 out of 1001
237 out of 1001
238 out of 1001
239 out of 1001
240 out of 1001
241 out of 1001
242 out of 1001
243 out of 1001
244 out of 1001
245 out of 1001
246 out of 1001
247 out of 1001
248 out of 1001
249 out of 1001
250 out of 1001
251 out of 1001
252 out of 1001
253 out of 1001
254 out of 1001
255 out of 1001
256 out of 1001
257 out of 1001
258 out of 1001
259 out of 1001
260 out of 1001
261 out of 1001
262 out of 1001
263 out of 1001
264 out of 1001
265 out of 1001
266 out of 1001
267 out of 1001
268 out of 1001
269 out of 1001
270 out of 1001
271 out of 1001
272 out of 1001
273 out of 1001
274 out of 1001
275 out of 1001
276 out of 1001
277 out of 1001
278 out of 1001
279 out of 1001
280 out of 1001
281 out of 1001
282 out of 1001
283 out of 1001
284 out of 1001
285 out of 1001
286 out of 1001
287 out of 1001
288 out of 1001
289 out of 1001
290 out of 1001
291 out of 1001
292 out of 1001
293 out of 1001
294 out of 1001
295 out of 1001
296 out of 1001
297 out of 1001
298 out of 1001
299 out of 1001
300 out of 1001
301 out of 1001
302 out of 1001
303 out of 1001
304 out of 1001
305 out of 1001
306 out of 1001
307 out of 1001
308 out of 1001
309 out of 1001
310 out of 1001
311 out of 1001
312 out of 1001
313 out of 1001
314 out of 1001
315 out of 1001
316 out of 1001
317 out of 1001
318 out of 1001
319 out of 1001
320 out of 1001
321 out of 1001
322 out of 1001
323 out of 1001
324 out of 1001
325 out of 1001
326 out of 1001
327 out of 1001
328 out of 1001
329 out of 1001
330 out of 1001
331 out of 1001
332 out of 1001
333 out of 1001
334 out of 1001
335 out of 1001
336 out of 1001
337 out of 1001
338 out of 1001
339 out of 1001
340 out of 1001
341 out of 1001
342 out of 1001
343 out of 1001
344 out of 1001
345 out of 1001
346 out of 1001
347 out of 1001
348 out of 1001
349 out of 1001
350 out of 1001
351 out of 1001
352 out of 1001
353 out of 1001
354 out of 1001
355 out of 1001
356 out of 1001
357 out of 1001
358 out of 1001
359 out of 1001
360 out of 1001
361 out of 1001
362 out of 1001
363 out of 1001
364 out of 1001
365 out of 1001
366 out of 1001
367 out of 1001
368 out of 1001
369 out of 1001
370 out of 1001
371 out of 1001
372 out of 1001
373 out of 1001
374 out of 1001
375 out of 1001
376 out of 1001
377 out of 1001
378 out of 1001
379 out of 1001
380 out of 1001
381 out of 1001
382 out of 1001
383 out of 1001
384 out of 1001
385 out of 1001
386 out of 1001
387 out of 1001
388 out of 1001
389 out of 1001
390 out of 1001
391 out of 1001
392 out of 1001
393 out of 1001
394 out of 1001
395 out of 1001
396 out of 1001
397 out of 1001
398 out of 1001
399 out of 1001
400 out of 1001
401 out of 1001
402 out of 1001
403 out of 1001
404 out of 1001
405 out of 1001
406 out of 1001
407 out of 1001
408 out of 1001
409 out of 1001
410 out of 1001
411 out of 1001
412 out of 1001
413 out of 1001
414 out of 1001
415 out of 1001
416 out of 1001
417 out of 1001
418 out of 1001
419 out of 1001
420 out of 1001
421 out of 1001
422 out of 1001
423 out of 1001
424 out of 1001
425 out of 1001
426 out of 1001
427 out of 1001
428 out of 1001
429 out of 1001
430 out of 1001
431 out of 1001
432 out of 1001
433 out of 1001
434 out of 1001
435 out of 1001
436 out of 1001
437 out of 1001
438 out of 1001
439 out of 1001
440 out of 1001
441 out of 1001
442 out of 1001
443 out of 1001
444 out of 1001
445 out of 1001
446 out of 1001
447 out of 1001
448 out of 1001
449 out of 1001
450 out of 1001
451 out of 1001
452 out of 1001
453 out of 1001
454 out of 1001
455 out of 1001
456 out of 1001
457 out of 1001
458 out of 1001
459 out of 1001
460 out of 1001
461 out of 1001
462 out of 1001
463 out of 1001
464 out of 1001
465 out of 1001
466 out of 1001
467 out of 1001
468 out of 1001
469 out of 1001
470 out of 1001
471 out of 1001
472 out of 1001
473 out of 1001
474 out of 1001
475 out of 1001
476 out of 1001
477 out of 1001
478 out of 1001
479 out of 1001
480 out of 1001
481 out of 1001
482 out of 1001
483 out of 1001
484 out of 1001
485 out of 1001
486 out of 1001
487 out of 1001
488 out of 1001
489 out of 1001
490 out of 1001
491 out of 1001
492 out of 1001
493 out of 1001
494 out of 1001
495 out of 1001
496 out of 1001
497 out of 1001
498 out of 1001
499 out of 1001
500 out of 1001
501 out of 1001
502 out of 1001
503 out of 1001
504 out of 1001
505 out of 1001
506 out of 1001
507 out of 1001
508 out of 1001
509 out of 1001
510 out of 1001
511 out of 1001
512 out of 1001
513 out of 1001
514 out of 1001
515 out of 1001
516 out of 1001
517 out of 1001
518 out of 1001
519 out of 1001
520 out of 1001
521 out of 1001
522 out of 1001
523 out of 1001
524 out of 1001
525 out of 1001
526 out of 1001
527 out of 1001
528 out of 1001
529 out of 1001
530 out of 1001
531 out of 1001
532 out of 1001
533 out of 1001
534 out of 1001
535 out of 1001
536 out of 1001
537 out of 1001
538 out of 1001
539 out of 1001
540 out of 1001
541 out of 1001
542 out of 1001
543 out of 1001
544 out of 1001
545 out of 1001
546 out of 1001
547 out of 1001
548 out of 1001
549 out of 1001
550 out of 1001
551 out of 1001
552 out of 1001
553 out of 1001
554 out of 1001
555 out of 1001
556 out of 1001
557 out of 1001
558 out of 1001
559 out of 1001
560 out of 1001
561 out of 1001
562 out of 1001
563 out of 1001
564 out of 1001
565 out of 1001
566 out of 1001
567 out of 1001
568 out of 1001
569 out of 1001
570 out of 1001
571 out of 1001
572 out of 1001
573 out of 1001
574 out of 1001
575 out of 1001
576 out of 1001
577 out of 1001
578 out of 1001
579 out of 1001
580 out of 1001
581 out of 1001
582 out of 1001
583 out of 1001
584 out of 1001
585 out of 1001
586 out of 1001
587 out of 1001
588 out of 1001
589 out of 1001
590 out of 1001
591 out of 1001
592 out of 1001
593 out of 1001
594 out of 1001
595 out of 1001
596 out of 1001
597 out of 1001
598 out of 1001
599 out of 1001
600 out of 1001
601 out of 1001
602 out of 1001
603 out of 1001
604 out of 1001
605 out of 1001
606 out of 1001
607 out of 1001
608 out of 1001
609 out of 1001
610 out of 1001
611 out of 1001
612 out of 1001
613 out of 1001
614 out of 1001
615 out of 1001
616 out of 1001
617 out of 1001
618 out of 1001
619 out of 1001
620 out of 1001
621 out of 1001
622 out of 1001
623 out of 1001
624 out of 1001
625 out of 1001
626 out of 1001
627 out of 1001
628 out of 1001
629 out of 1001
630 out of 1001
631 out of 1001
632 out of 1001
633 out of 1001
634 out of 1001
635 out of 1001
636 out of 1001
637 out of 1001
638 out of 1001
639 out of 1001
640 out of 1001
641 out of 1001
642 out of 1001
643 out of 1001
644 out of 1001
645 out of 1001
646 out of 1001
647 out of 1001
648 out of 1001
649 out of 1001
650 out of 1001
651 out of 1001
652 out of 1001
653 out of 1001
654 out of 1001
655 out of 1001
656 out of 1001
657 out of 1001
658 out of 1001
659 out of 1001
660 out of 1001
661 out of 1001
662 out of 1001
663 out of 1001
664 out of 1001
665 out of 1001
666 out of 1001
667 out of 1001
668 out of 1001
669 out of 1001
670 out of 1001
671 out of 1001
672 out of 1001
673 out of 1001
674 out of 1001
675 out of 1001
676 out of 1001
677 out of 1001
678 out of 1001
679 out of 1001
680 out of 1001
681 out of 1001
682 out of 1001
683 out of 1001
684 out of 1001
685 out of 1001
686 out of 1001
687 out of 1001
688 out of 1001
689 out of 1001
690 out of 1001
691 out of 1001
692 out of 1001
693 out of 1001
694 out of 1001
695 out of 1001
696 out of 1001
697 out of 1001
698 out of 1001
699 out of 1001
700 out of 1001
701 out of 1001
702 out of 1001
703 out of 1001
704 out of 1001
705 out of 1001
706 out of 1001
707 out of 1001
708 out of 1001
709 out of 1001
710 out of 1001
711 out of 1001
712 out of 1001
713 out of 1001
714 out of 1001
715 out of 1001
716 out of 1001
717 out of 1001
718 out of 1001
719 out of 1001
720 out of 1001
721 out of 1001
722 out of 1001
723 out of 1001
724 out of 1001
725 out of 1001
726 out of 1001
727 out of 1001
728 out of 1001
729 out of 1001
730 out of 1001
731 out of 1001
732 out of 1001
733 out of 1001
734 out of 1001
735 out of 1001
736 out of 1001
737 out of 1001
738 out of 1001
739 out of 1001
740 out of 1001
741 out of 1001
742 out of 1001
743 out of 1001
744 out of 1001
745 out of 1001
746 out of 1001
747 out of 1001
748 out of 1001
749 out of 1001
750 out of 1001
751 out of 1001
752 out of 1001
753 out of 1001
754 out of 1001
755 out of 1001
756 out of 1001
757 out of 1001
758 out of 1001
759 out of 1001
760 out of 1001
761 out of 1001
762 out of 1001
763 out of 1001
764 out of 1001
765 out of 1001
766 out of 1001
767 out of 1001
768 out of 1001
769 out of 1001
770 out of 1001
771 out of 1001
772 out of 1001
773 out of 1001
774 out of 1001
775 out of 1001
776 out of 1001
777 out of 1001
778 out of 1001
779 out of 1001
780 out of 1001
781 out of 1001
782 out of 1001
783 out of 1001
784 out of 1001
785 out of 1001
786 out of 1001
787 out of 1001
788 out of 1001
789 out of 1001
790 out of 1001
791 out of 1001
792 out of 1001
793 out of 1001
794 out of 1001
795 out of 1001
796 out of 1001
797 out of 1001
798 out of 1001
799 out of 1001
800 out of 1001
801 out of 1001
802 out of 1001
803 out of 1001
804 out of 1001
805 out of 1001
806 out of 1001
807 out of 1001
808 out of 1001
809 out of 1001
810 out of 1001
811 out of 1001
812 out of 1001
813 out of 1001
814 out of 1001
815 out of 1001
816 out of 1001
817 out of 1001
818 out of 1001
819 out of 1001
820 out of 1001
821 out of 1001
822 out of 1001
823 out of 1001
824 out of 1001
825 out of 1001
826 out of 1001
827 out of 1001
828 out of 1001
829 out of 1001
830 out of 1001
831 out of 1001
832 out of 1001
833 out of 1001
834 out of 1001
835 out of 1001
836 out of 1001
837 out of 1001
838 out of 1001
839 out of 1001
840 out of 1001
841 out of 1001
842 out of 1001
843 out of 1001
844 out of 1001
845 out of 1001
846 out of 1001
847 out of 1001
848 out of 1001
849 out of 1001
850 out of 1001
851 out of 1001
852 out of 1001
853 out of 1001
854 out of 1001
855 out of 1001
856 out of 1001
857 out of 1001
858 out of 1001
859 out of 1001
860 out of 1001
861 out of 1001
862 out of 1001
863 out of 1001
864 out of 1001
865 out of 1001
866 out of 1001
867 out of 1001
868 out of 1001
869 out of 1001
870 out of 1001
871 out of 1001
872 out of 1001
873 out of 1001
874 out of 1001
875 out of 1001
876 out of 1001
877 out of 1001
878 out of 1001
879 out of 1001
880 out of 1001
881 out of 1001
882 out of 1001
883 out of 1001
884 out of 1001
885 out of 1001
886 out of 1001
887 out of 1001
888 out of 1001
889 out of 1001
890 out of 1001
891 out of 1001
892 out of 1001
893 out of 1001
894 out of 1001
895 out of 1001
896 out of 1001
897 out of 1001
898 out of 1001
899 out of 1001
900 out of 1001
901 out of 1001
902 out of 1001
903 out of 1001
904 out of 1001
905 out of 1001
906 out of 1001
907 out of 1001
908 out of 1001
909 out of 1001
910 out of 1001
911 out of 1001
912 out of 1001
913 out of 1001
914 out of 1001
915 out of 1001
916 out of 1001
917 out of 1001
918 out of 1001
919 out of 1001
920 out of 1001
921 out of 1001
922 out of 1001
923 out of 1001
924 out of 1001
925 out of 1001
926 out of 1001
927 out of 1001
928 out of 1001
929 out of 1001
930 out of 1001
931 out of 1001
932 out of 1001
933 out of 1001
934 out of 1001
935 out of 1001
936 out of 1001
937 out of 1001
938 out of 1001
939 out of 1001
940 out of 1001
941 out of 1001
942 out of 1001
943 out of 1001
944 out of 1001
945 out of 1001
946 out of 1001
947 out of 1001
948 out of 1001
949 out of 1001
950 out of 1001
951 out of 1001
952 out of 1001
953 out of 1001
954 out of 1001
955 out of 1001
956 out of 1001
957 out of 1001
958 out of 1001
959 out of 1001
960 out of 1001
961 out of 1001
962 out of 1001
963 out of 1001
964 out of 1001
965 out of 1001
966 out of 1001
967 out of 1001
968 out of 1001
969 out of 1001
970 out of 1001
971 out of 1001
972 out of 1001
973 out of 1001
974 out of 1001
975 out of 1001
976 out of 1001
977 out of 1001
978 out of 1001
979 out of 1001
980 out of 1001
981 out of 1001
982 out of 1001
983 out of 1001
984 out of 1001
985 out of 1001
986 out of 1001
987 out of 1001
988 out of 1001
989 out of 1001
990 out of 1001
991 out of 1001
992 out of 1001
993 out of 1001
994 out of 1001
995 out of 1001
996 out of 1001
997 out of 1001
998 out of 1001
999 out of 1001
1000 out of 1001